### ISSUE TITLE
奇怪的分词错误。

### ISSUE THREAD

**Issue by zhangyyz** [yizhiru/thulac4j#13]
使用Segmenter.segment的时候，发现有些时候分词有奇怪错误。

例如：
"要想不迟到，就得早点起床。"  分词结果为： 要/**想不迟**/到/ ，/就/得/早/点儿/起床/。

第二个例子：
"黄酒是最古老的酒之一。"分词结果为： 黄酒/是/最/古老/的/**酒之一**/。

不知为什么Segmenter.segment会把"想不迟"和“酒之一”当作一个词。

**Comment by yizhiru** [comment]
@zhangyyz 对比了原版分词结果，也是这样：
要/, 想不迟/, 到/, ，/, 就/, 得/, 早/, 点/, 起床/, 。/
黄酒/, 是/, 最/, 古老/, 的/, 酒之一/, 。/

原因是训练模型存在误分词的情况。
