### ISSUE TITLE
有些词没有被识别出来。

### ISSUE THREAD

**Issue by zhangyyz** [yizhiru/thulac4j#14]
例如：
“只有一个人”，在原版Demo里( http://thulac.thunlp.org/demo )的分词为： 只有_c 一_m 个_q 人_n 。_w
但是thulac4j的分词为：  只/d 有/v 一个/m 人/n 。/w

“只有”这个词在thulac4j里没有被识别出来。

**Comment by yizhiru** [comment]
@zhangyyz 在thulac的python原版中，分词结果为 [['只', 'd'], ['有', 'v'], ['一个', 'm'], ['人', 'n']]，java原版的结果也类似。
