### ISSUE TITLE
@wenming5112 你好，需要在thulac的官网下载这些模型文件，或者解压thulac4j的jar包，也可以拿到

### ISSUE THREAD

**Issue by koalton** [yizhiru/thulac4j#15]
@wenming5112 你好，需要在thulac的官网下载这些模型文件，或者解压thulac4j的jar包，也可以拿到

_Originally posted by @yizhiru in https://github.com/yizhiru/thulac4j/issues/12#issuecomment-445773007_

==============
您好，发现解压thulac4j.jar后，发现里面的models目录下并没有Test中使用的两个文件：【models/model_c_model.bin", "models/model_c_dat.bin】，但是包含其它的一些文件，所以如果需要使用带词性的分词结果，thulac4j中的这块代码应该如何填写入参？ POSTagger pos = new POSTagger("models/model_c_model.bin", "models/model_c_dat.bin");

**Comment by yizhiru** [comment]
@koalton 上述两个文件是词性标注依赖的模型文件，由于文件太大并没有打入到jar包中，请到官网中下载完整的模型文件。
