### ISSUE TITLE
idiom_dat.bin的数据存储内容是什么样的

### ISSUE THREAD

**Issue by chaochaoSZ** [yizhiru/thulac4j#20]
如题，.bin文件的存储内容是什么样子的。我想把词典也存储成相似的格式。

**Comment by yizhiru** [comment]
@chaochaoSZ idiom_dat.bin存储的是成语词典，数据结构是Double Array Trie，词典生成DAT、序列化、加载等方法可参看类DoubleArrayTrie

**Comment by chaochaoSZ** [comment]
是这样，原始的模型是.dat格式的，但是在你的模型里用的使用的时候好像会重新生成一个bin

**Comment by yizhiru** [comment]
本项目中的词典在官方词典的基础上做了新增与修改，保存格式也不一样了
